void setup();
void ProcesamientoDeInformacion();
void acelerometroInicializacion();
void gpsInicialization();
void tempInicialization();
void sdInitialization();
double *acelerometro();
bool acelerometroAlto ();
String *gpsDatos();
String *tempyhumedad();
void pinesyvariables();
void EncenderDispositivos();
void ApagarDispositivos();
void saveData(String, int);
void wifiInicializacion();
void httpmyRequest(String, String, String, String, String, String, String, String, String);
